# source : pve1:/etc/pve/ceph.conf
# releve le : 27/08/2026 — copie documentaire, verifier avec scripts/check-drift.sh
[global]
	auth_client_required = cephx
	auth_cluster_required = cephx
	auth_service_required = cephx
	cluster_network = 10.200.0.0/24
	fsid = 08c111f7-4af0-46dc-bc3b-9ca7f358a80f
	mon_allow_pool_delete = true
	mon_host = 10.200.0.11 10.200.0.12 10.200.0.13
	ms_bind_ipv4 = true
	ms_bind_ipv6 = false
	osd_pool_default_min_size = 2
	osd_pool_default_size = 3
	public_network = 10.200.0.0/24

[client]
	keyring = /etc/pve/priv/$cluster.$name.keyring

[client.crash]
	keyring = /etc/pve/ceph/$cluster.$name.keyring

[mon.pve1]
	public_addr = 10.200.0.11

[mon.pve2]
	public_addr = 10.200.0.12

[mon.pve3]
	public_addr = 10.200.0.13

